config/routes.rb
Rails.application.routes.draw do
  delete '/wishlist/:id', to: "wishlists#destroy", as: "destroy_user_wishlist"
  get '/seller-history', to: "home_pages#seller_history", as: "seller_history"
  get '/search', to: "home_pages#search", as: "search"
  get '/my-orders', to: "orders#my_orders", as: "my_orders"
  post '/create-order', to: "orders#create_order", as: "create_order"
  get '/checkout', to: "home_pages#checkout", as: "checkout"
  get 'order-summary', to: "orders#order_summary", as: "order_summary"
  post '/users/:user_id/address', to: "addresses#create", as: "create_user_address"
  put '/users/:user_id/address/:id', to: "addresses#update", as: "update_user_address"
  delete '/users/:user_id/address/:id', to: "addresses#destroy", as: "delete_user_address"
  put '/products/update', to: "carts#update_cart_item", as: "update_cart_item"
  delete '/products/:product_id', to: "carts#delete_cart_item", as: "delete_cart_item"
  post '/products/:product_id/reviews/new', to: "reviews#create", as: "create_product_review"
  put '/products/:product_id/reviews/:id', to: "reviews#update", as: "update_product_review"
  delete '/products/:product_id/reviews/:id', to: "reviews#destroy", as: "destroy_product_review"
  get '/wishlist', to: "wishlists#my_wishlist", as: "my_wishlist"
  get '/cart', to: "carts#my_cart", as: "my_cart"
  post '/products/add', to: "carts#add_product_to_cart", as: "add_product_to_cart"
  post '/products/wishlist', to: "wishlists#add_product_to_wishlist", as: "add_product_to_wishlist"
  get '/products/category/:category_id', to: "home_pages#products_by_category", as: "products_by_category"
  get '/products/:id', to: "products#show", as: "product_show"
  delete '/products/:id/image/:image_id', to: "products#remove_product_image", as: "remove_product_image"
  post '/sellers/:seller_id/products/new', to: "products#create"
  delete '/sellers/:seller_id/products/:id', to: "products#destroy", as: "delete_seller_product"
  put '/sellers/:seller_id/products/:id', to: "products#update", as: "update_seller_product"

  resources :sellers do
    resources :products
  end
  resources :products do
    resources :reviews
  end
  root to: "home_pages#index"
  get 'home_pages/index'
  devise_for :users, controllers: {sessions: 'users/sessions', :registrations => "users/registrations",
  }
  resources :users do
    resources :addresses
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/home_pages_controller.rb
class HomePagesController < ApplicationController
  include CartsHelper

  def index
    @categories = Product.categories
    @verticals = Product.verticals
  end

  # GET /products/category/:category_id
  def products_by_category
    @products = Product.where(category: params[:category_id])
  end

  #GET /checkout
  def checkout
    @addresses = current_user.address
  end

  # GET /search
  # params - title
  def search
    # TODO use like operator
    @search_results = Product.where(title: params[:title])
  end

  #GET /seller-history
  def seller_history
    @sold_products = current_user.seller.order_line_items.group(:product_id).sum(:quantity)
    @total_revenue = 0
    @sold_products.each do |pid, qty|
      @total_revenue += get_product_price(pid, qty)
    end
  end
end

app/helpers/home_pages_helper.rb
module HomePagesHelper
end

app/views/home_pages/_product.html.haml
.container.mt-5
  %h3
    =link_to product.title, product_show_path(product), method: :get
  %li
    Description -
    = product.description
  %li
    Price -
    = product.price
  %li
    id -
    = product.id
  %p
    - product.images.each do |img|
      = image_tag(img, size: "50x50")

app/views/home_pages/checkout.html.haml
.container.mt-5
  -if @addresses.length > 0
    %h4
      Please Select An Address
    =form_with(url: update_cart_item_path, html: {method: :put}) do |f|
      -@addresses.each do |address|
        =f.hidden_field :redirect, :value => checkout_path
        =f.radio_button(:current_address, address.id, :checked => address.id.to_i == session[:current_address].to_i)
        %ul
          = render 'addresses/address', address: address
        %br
      .actions
        =f.submit 'Select'
  %br
    %br
    %p
      =link_to 'Add a new address', new_user_address_path(current_user.id, :redirect => checkout_path), class: "text-info"
  -if session[:current_address]
    .btn.btn-primary
      =link_to 'Continue', order_summary_path
  -else
    Please Select An Address To Continue

app/views/home_pages/index.html.haml
=provide(:title, full_title("Home"))

-# =current_seller
%h4.mt-5
  Hi There!
  =current_user.email
  =current_user.is_seller
.container.mt-5.pt-5
  .top
    - if current_seller
      %h4
        .btn.btn-info
          = link_to "Add a product", new_seller_product_path(@current_seller)
  -# =form_with(url: )
  =form_with(url: search_path, html: {method: :get}, local: true ) do |f|
    .field
      -# =f.label :SearchProducts
      =f.text_field :title
    .actions
      =f.submit 'Search'
  .categories
    Browse Product By Categories
    %br
      - @categories.each  do |category|
        %br
          %li.btn.btn-success=link_to category[0], products_by_category_path(category[1])

app/views/home_pages/my_cart.html.haml
.container
  %h2.mt-5.mt-6
    Your Cart
  - if @cart_items && @cart_items.keys.length > 0
    -@cart_items.each do |product_id, quantity|
      .row
        - if !(product_id.nil? && quantity.nil?) && Product.find_by(id: product_id)
          .col.col-xs
            =render "product", product: Product.find_by(id: product_id)
          .col.col-xs
            %h4
              Quantity
              =form_with(url: update_cart_item_path, method: :put) do |f|
                = f.hidden_field :product_id, :value => product_id
                = f.number_field :quantity, :value => quantity, min: 0
                .actions
                = f.submit "Update Quantity"
                %br
              -# = quantity
              %br
              %btn.btn.btn-danger
                =link_to "Remove From Cart", delete_cart_item_path(product_id), method: :delete
  - else
    There are no items in your cart.
  %footer.mt-5
    - if session[:products] && session[:products].values.select {|v| v.to_i > 0}.length > 0
      %btn.btn.btn-danger
        =link_to 'Proceed To Checkout', checkout_path

app/views/home_pages/my_wishlist.html.haml
.alert-success
.container.mt-5
  -if @wishlists && @wishlists.length > 0
    -@wishlists.each do |wishlist|
      = render "product", product: wishlist.product
      -#.btn.btn-success
      -#  =link_to "Add To Cart", add_product_to_cart_path, method: :post
      %span#cart_link= link_to add_product_to_cart_url
      %span#product_id=wishlist.product.id
      .card
        Select Quantity
        %btn.btn.btn-primary#add +
        %span#quantity
        %btn.btn.btn-danger#sub -
      %br
      %btn.btn.btn-success#addToCart +Add To Cart
  -else
    There are no items in your wishlist.
%script{:type=>"text/javascript"}
  var quantity = 1
  -#document.getElementById('test').innerText =
  document.getElementById('quantity').innerText = quantity
  document.getElementById('add').addEventListener('click', () => {quantity += 1; document.getElementById('quantity').innerText = quantity})
  document.getElementById('sub').addEventListener('click', () => {quantity -= 1; quantity = quantity > 0 ? quantity : 1; document.getElementById('quantity').innerText = quantity})
  -#-#document.getElementById('addToWishList').addEventListener('click', () => {})
  document.getElementById('addToCart').addEventListener('click',  () => {
  const res = fetch(document.getElementById('cart_link').firstChild.innerHTML,
  {
  method: 'POST',
  body: JSON.stringify({product_id: document.getElementById('product_id').innerText, quantity: quantity, wishlist: true}),
  'Content-Type': 'application/json',
  'Accept': 'application/json',
  headers: {'X-CSRF-Token':document.getElementsByName("csrf-token")[0].getAttribute("content")}
  })
  res.then((el) => (el.json())).then((el) =>{const doc = document.getElementsByClassName('alert-success')[0]; doc.innerText = el.message; setTimeout(() => doc.innerText = "", 2000)})
  })

app/views/home_pages/products_by_category.html.haml
-@products.each do |product|
  = render "product", product: product
  -if @products.length == 0
    There are no products in this category.

app/views/home_pages/search.html.haml
.container.mt-5
  %h4
    Results for your search
  -if @search_results && @search_results.length > 0
    -@search_results.each do |product|
      = render 'home_pages/product', product: product
  -else
    No Results Found. Please Try Different Search Keywords.
  %br
    %br
      %footer
        =link_to "Back", root_path

app/views/home_pages/seller_history.html.haml
.container.mt-5
  %h4 Total Revenue is -
  =@total_revenue
  %h4 Sold Products
  -@sold_products.each do |pid, qty|
    =render "home_pages/product", product: Product.find(pid)
    Quantity
    =qty || 0