config/routes.rb
Rails.application.routes.draw do
  delete '/wishlist/:id', to: "wishlists#destroy", as: "destroy_user_wishlist"
  get '/seller-history', to: "home_pages#seller_history", as: "seller_history"
  get '/search', to: "home_pages#search", as: "search"
  get '/my-orders', to: "orders#my_orders", as: "my_orders"
  post '/create-order', to: "orders#create_order", as: "create_order"
  get '/checkout', to: "home_pages#checkout", as: "checkout"
  get 'order-summary', to: "orders#order_summary", as: "order_summary"
  post '/users/:user_id/address', to: "addresses#create", as: "create_user_address"
  put '/users/:user_id/address/:id', to: "addresses#update", as: "update_user_address"
  delete '/users/:user_id/address/:id', to: "addresses#destroy", as: "delete_user_address"
  put '/products/update', to: "carts#update_cart_item", as: "update_cart_item"
  delete '/products/:product_id', to: "carts#delete_cart_item", as: "delete_cart_item"
  post '/products/:product_id/reviews/new', to: "reviews#create", as: "create_product_review"
  put '/products/:product_id/reviews/:id', to: "reviews#update", as: "update_product_review"
  delete '/products/:product_id/reviews/:id', to: "reviews#destroy", as: "destroy_product_review"
  get '/wishlist', to: "wishlists#my_wishlist", as: "my_wishlist"
  get '/cart', to: "carts#my_cart", as: "my_cart"
  post '/products/add', to: "carts#add_product_to_cart", as: "add_product_to_cart"
  post '/products/wishlist', to: "wishlists#add_product_to_wishlist", as: "add_product_to_wishlist"
  get '/products/category/:category_id', to: "home_pages#products_by_category", as: "products_by_category"
  get '/products/:id', to: "products#show", as: "product_show"
  delete '/products/:id/image/:image_id', to: "products#remove_product_image", as: "remove_product_image"
  post '/sellers/:seller_id/products/new', to: "products#create"
  delete '/sellers/:seller_id/products/:id', to: "products#destroy", as: "delete_seller_product"
  put '/sellers/:seller_id/products/:id', to: "products#update", as: "update_seller_product"

  resources :sellers do
    resources :products
  end
  resources :products do
    resources :reviews
  end
  root to: "home_pages#index"
  get 'home_pages/index'
  devise_for :users, controllers: {sessions: 'users/sessions', :registrations => "users/registrations",
  }
  resources :users do
    resources :addresses
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  # before_action {@@redirect_path = nil}
  before_action :set_address, only: [:edit, :update, :destroy]
  after_action :remove_redirect, only: [:update, :destroy]
  def index
    @addresses = current_user.addresses
  end

  def edit
    # puts "params, #{params[:redirect]}"
    @@redirect_path = params[:redirect]
  end

  def update
    # @address = current_user.address.new(address_params)
    if @address.update(address_params)
      puts "redirect path #{@redirect_path}"
      puts "params #{params}"
      redirect_to @@redirect_path || users_addresses_path(@address, notice: "Address was created successfully")
    else
      render 'new'
    end
  end

  def new
    @@redirect_path = params[:redirect]
    @address = current_user.address.new
  end

  def create
    @address = current_user.address.new(address_params)
    if @address.save
      redirect_to @@redirect_path || users_address_path(@address, notice: "Address was created successfully")
    else
      render 'new'
    end
  end

  def destroy
    puts "called"
    session.delete(:current_address)
    @address.destroy
    current_user.save
    redirect_to params[:redirect]
  end

  private
  def set_address
    # puts "params #{params}"
    # @@redirect_path = nil
    @address = current_user.address.find(params[:id])
  end
  def address_params
    params.require(:address).permit([:locality, :state, :country, :pin_code, :address_type])
  end
  def remove_redirect
    @@redirect_path = nil
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/views/addresses/_address.html.haml
Locality -
=address.locality
%br
State -
=address.state
%br
Pin Code -
=address.pin_code
%br
Address Type -
=address.address_type
%br
  - if ! (local_assigns[:remove_actions])
    .btn.btn-success
      =link_to 'edit', edit_user_address_path(current_user.id, address.id, :redirect => checkout_path)
    .btn.btn-danger
      =link_to 'delete', delete_user_address_path(current_user.id, address.id, :redirect => checkout_path), method: :delete

app/views/addresses/_form.html.haml
- if @address.errors.any?
  #error_explanation
    %h2= "#{pluralize(@address.errors.count, "error")} prohibited this product from being saved:"
    %ul
      - @address.errors.full_messages.each do |message|
        %li= message
.field
  = f.label :locality
  = f.text_field :locality
.field
  = f.label :state
  = f.text_field :state
.field
  = f.label :country
  = f.text_field :country
.field
  = f.label :pin_code
  = f.number_field :pin_code
.field
  = f.label :address_type
  = f.select :address_type, options_for_select(Address.address_types.map {|k,v| [k.humanize.capitalize, k]})
.actions
  = f.submit 'Save'

app/views/addresses/destroy.html.haml
%h1 Addresses#destroy
%p Find me in app/views/addresses/destroy.html.haml

app/views/addresses/edit.html.haml
.container.mt-5
  %h4
    Edit address
    =@address.id
  =form_for(@address, url: update_user_address_path(current_user.id,@address.id), html: {method: :put}) do |f|
    = render 'form', f: f

app/views/addresses/index.html.haml
%h1 Addresses#index
%p Find me in app/views/addresses/index.html.haml

app/views/addresses/new.html.haml
.container.mt-5
  %h4
    Add a new address
  =form_for(@address, url: create_user_address_path, html: {method: :post}) do |f|
    = render 'form', f: f

app/views/addresses/update.html.haml
%h1 Addresses#update
%p Find me in app/views/addresses/update.html.haml