config/routes.rb
Rails.application.routes.draw do
  delete '/wishlist/:id', to: "wishlists#destroy", as: "destroy_user_wishlist"
  get '/seller-history', to: "home_pages#seller_history", as: "seller_history"
  get '/search', to: "home_pages#search", as: "search"
  get '/my-orders', to: "orders#my_orders", as: "my_orders"
  post '/create-order', to: "orders#create_order", as: "create_order"
  get '/checkout', to: "home_pages#checkout", as: "checkout"
  get 'order-summary', to: "orders#order_summary", as: "order_summary"
  post '/users/:user_id/address', to: "addresses#create", as: "create_user_address"
  put '/users/:user_id/address/:id', to: "addresses#update", as: "update_user_address"
  delete '/users/:user_id/address/:id', to: "addresses#destroy", as: "delete_user_address"
  put '/products/update', to: "carts#update_cart_item", as: "update_cart_item"
  delete '/products/:product_id', to: "carts#delete_cart_item", as: "delete_cart_item"
  post '/products/:product_id/reviews/new', to: "reviews#create", as: "create_product_review"
  put '/products/:product_id/reviews/:id', to: "reviews#update", as: "update_product_review"
  delete '/products/:product_id/reviews/:id', to: "reviews#destroy", as: "destroy_product_review"
  get '/wishlist', to: "wishlists#my_wishlist", as: "my_wishlist"
  get '/cart', to: "carts#my_cart", as: "my_cart"
  post '/products/add', to: "carts#add_product_to_cart", as: "add_product_to_cart"
  post '/products/wishlist', to: "wishlists#add_product_to_wishlist", as: "add_product_to_wishlist"
  get '/products/category/:category_id', to: "home_pages#products_by_category", as: "products_by_category"
  get '/products/:id', to: "products#show", as: "product_show"
  delete '/products/:id/image/:image_id', to: "products#remove_product_image", as: "remove_product_image"
  post '/sellers/:seller_id/products/new', to: "products#create"
  delete '/sellers/:seller_id/products/:id', to: "products#destroy", as: "delete_seller_product"
  put '/sellers/:seller_id/products/:id', to: "products#update", as: "update_seller_product"

  resources :sellers do
    resources :products
  end
  resources :products do
    resources :reviews
  end
  root to: "home_pages#index"
  get 'home_pages/index'
  devise_for :users, controllers: {sessions: 'users/sessions', :registrations => "users/registrations",
  }
  resources :users do
    resources :addresses
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  # default_scope -> {where("stock > ?", 0)}
  VERTICALS = {'MEN': 0, 'WOMEN': 1, 'ALL': 2}
  CATEGORIES = {'ELECTRONICS': 0, 'CLOTHING': 1, 'ACCESSORIES': 2, 'OTHER': 3}
  enum vertical: VERTICALS
  enum category: CATEGORIES
  belongs_to :seller
  has_many_attached :images, dependent: :destroy

  has_many :reviews, dependent: :destroy
  validates :seller, presence: true
  validates :name, :title, :description, :price, :stock, :vertical, :category, presence: true
  has_many :order_line_items
  has_many :orders, through: :order_line_items
  has_many :wishlists, dependent: :destroy
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:edit, :update, :destroy, :remove_product_image]
  before_action :validate_seller, only: [:edit, :update, :destroy]
  include ApplicationHelper
  # POST /products/:product_id/image/:image_id
  # remove_product_image
  def remove_product_image
    # puts "params #{params}"
    # ActiveStorage::Blob.find_signed(params[:image_id]).purge
    @product.images.find(params[:image_id]).purge
    # byebug
    redirect_to seller_product_path(current_seller.id, @product.id)
    # @product.images[params[:image_id]].purge
  end
  # GET /products
  # GET /products.json
  def index
    @products = current_seller.product.all
  end
  #  POST /products/add/:product_id
  def update_quantity
    # session[:cart][params[:product_id]]
  end
  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])
  end

  # GET /products/new
  def new
    @product ||= Product.new
    @product.seller_id = current_seller.id
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create

    @product = Product.new(product_params)
    @product.images.attach(params[:product][:images]) if params[:product][:images]

    respond_to do |format|
      if @product.save
        format.html { redirect_to seller_product_path(current_seller.id, @product.id), notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        puts "called #{params}"
        @product.images.attach(params[:product][:images]) if params[:product][:images]
        format.html { redirect_to seller_product_path(current_seller.id, @product.id), notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to seller_products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = current_seller.product.find(params[:id])
    end

  def validate_seller
    if current_user && current_user.seller.user_id == current_user.id
      true
    else
      redirect_to new_user_session
    end
  end
    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:seller_id, :name, :title, :description, :price, :stock, :vertical, :category, :discount, :images)
      # pramas['product']['vertical'].to_i!
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.haml
- if @product.errors.any?
  #error_explanation
    %h2= "#{pluralize(@product.errors.count, "error")} prohibited this product from being saved:"
    %ul
      - @product.errors.full_messages.each do |message|
        %li= message

.field
  = f.label :seller_id
  = f.number_field :seller_id
.field
  = f.label :name
  = f.text_field :name
.field
  = f.label :title
  = f.text_field :title
.field
  = f.label :description
  = f.text_field :description
.field
  = f.label :price
  = f.number_field :price
.field
  = f.label :stock
  = f.number_field :stock
.field
  = f.label :vertical
  = f.select :vertical, options_for_select(Product.verticals.map {|k,v| [k.humanize.capitalize, k.to_s]})
.field
  = f.label :category
  = f.select :category, options_for_select(Product.categories.map {|k,v| [k.humanize.capitalize, k.to_s]})
.field
  = f.label :discount
  = f.number_field :discount
.field
  = f.label :images
  = f.file_field :images, multiple: true
  .images
    -@product.images.map do |img, idx|
      -# =img.id
      =image_tag(img, size: "50x50")
      =link_to "remove image", remove_product_image_path(@product.id, img.id), :method => :delete
.actions
  = f.submit 'Save'

app/views/products/edit.html.haml
%h1 Editing product
=form_for @product, url: update_seller_product_path(current_seller.id), html: { method: :put } do |f|
  = render 'form', f: f

= link_to 'Show', seller_product_path(current_seller, @product)
\|
= link_to 'Back', seller_products_path(current_seller)

app/views/products/index.html.haml
%h1 Listing products

%table
  %thead
    %tr
      %th Seller
      %th Name
      %th Title
      %th Description
      %th Price
      %th Stock
      %th Vertical
      %th Category
      %th Discount
      %th Has Images
      %th
      %th

  %tbody
    - @products.each do |product|
      %tr
        %td= product.seller.user.name
        %td= product.name
        %td= product.title
        %td= product.description
        %td= product.price
        %td= product.stock
        %td= product.vertical
        %td= product.category
        %td= product.discount
        %td= product.images.attached?
        %td= link_to 'Show', seller_product_path(current_seller, product)
        %td= link_to 'Edit', edit_seller_product_path(current_seller, product)
        %td= link_to 'Destroy', delete_seller_product_path(current_seller, product), method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Product', new_seller_product_path

app/views/products/new.html.haml
%h1 New product
=form_for @product, url: new_seller_product_path(current_seller.id), html: { method: :post } do |f|
  = render 'form', f: f

= link_to 'Back', seller_products_path

app/views/products/show.html.haml
%p#notice= notice
.mt-5.pt-5
  .alert-success
  .alert-success.wishlist
  %h3.head
    = @product.name
  .top-div
    .col-6
      %p
        %b Name:
        = @product.name
      %p
        %b Title:
        = @product.title
      %p
        %b Description:
        = @product.description
      %p
        %b Price:
        = @product.price
      %p
        %b Stock
        %span#stock
          = @product.stock
      %p
        %b Vertical:
        = @product.vertical
      %p
        %b Category:
        = @product.category
      %p
        %b Discount:
        = @product.discount
      %p
        %b Sold By:
        = @product.seller.user.name

      - if current_seller
        = link_to 'Edit', edit_seller_product_path(current_seller.id, @product)
        = link_to 'Back', seller_products_path(current_seller)
      .card
        Select Quantity
        %btn.btn.btn-primary#add +
        %span#quantity
        %btn.btn.btn-danger#sub -
    .col-6.image-container
      %p
      - @product.images.each do |img|
        = image_tag(img, size: "50x50")
  %br
  -if @product.stock > 0
    %btn.btn.btn-success#addToCart +Add To Cart
  -else
    This Product is out of Stock
  |
  %btn.btn.btn-success#addToWishList +Add To WishList
  %span#cart_link= link_to add_product_to_cart_url
  %span#wishlist_link= link_to add_product_to_wishlist_url
  %span#product_id=@product.id
  %span#status
  = csrf_meta_tag
.mt-5
%btn.btn.btn-danger
  =link_to "Write A Review", new_product_review_path(@product.id)
%h3
  List of Reviews
  -@product.reviews.each do |review|
    %h4
      Review By
      = review.user.name
    %h4= review.title
    %h6
      %b
        Ratings -
      %b
        = review.ratings
        Stars
    %p= review.description
    - if review.user.id == current_user.id
      =link_to "Edit", edit_product_review_path(@product.id, review.id)
      =link_to "Delete", destroy_product_review_path(@product.id, review.id), method: :delete
%script{:type=>"text/javascript"}
  var quantity = 0
  -#document.getElementById('test').innerText =
  document.getElementById('quantity').innerText = quantity
  const stock = parseInt(document.getElementById('stock').innerText)
  document.getElementById('add').addEventListener('click', () => {quantity += 1; quantity = quantity > stock ? stock : quantity; document.getElementById('quantity').innerText = quantity})
  document.getElementById('sub').addEventListener('click', () => {quantity -= 1; quantity = quantity >= 0 ? quantity : 0; document.getElementById('quantity').innerText = quantity})
  -#-#document.getElementById('addToWishList').addEventListener('click', () => {})
  document.getElementById('addToCart').addEventListener('click',  () => {
  const res = fetch(document.getElementById('cart_link').firstChild.innerHTML,
  {
  method: 'POST',
  body: JSON.stringify({product_id: document.getElementById('product_id').innerText, quantity: quantity}),
  'Content-Type': 'application/json',
  'Accept': 'application/json',
  headers: {'X-CSRF-Token':document.getElementsByName("csrf-token")[0].getAttribute("content")}
  })
  res.then((el) => (el.json())).then((el) =>{const doc = document.getElementsByClassName('alert-success')[0]; doc.innerText = el.message; setTimeout(() => doc.innerText = "", 2000)})
  })
  document.getElementById('addToWishList').addEventListener('click',  () => {
  console.log('Hey There');
  const res = fetch(document.getElementById('wishlist_link').firstChild.innerHTML,
  {
  method: 'POST',
  body: JSON.stringify({product_id: document.getElementById('product_id').innerText}),
  'Content-Type': 'application/json',
  'Accept': 'application/json',
  headers: {'X-CSRF-Token':document.getElementsByName("csrf-token")[0].getAttribute("content")}
  })
  res.then((el) => (el.json())).then((el) =>{const doc = document.getElementsByClassName('wishlist')[0]; doc.innerText = el.message; setTimeout(() => doc.innerText = "", 2000)})
  });