config/routes.rb
Rails.application.routes.draw do
  delete '/wishlist/:id', to: "wishlists#destroy", as: "destroy_user_wishlist"
  get '/seller-history', to: "home_pages#seller_history", as: "seller_history"
  get '/search', to: "home_pages#search", as: "search"
  get '/my-orders', to: "orders#my_orders", as: "my_orders"
  post '/create-order', to: "orders#create_order", as: "create_order"
  get '/checkout', to: "home_pages#checkout", as: "checkout"
  get 'order-summary', to: "orders#order_summary", as: "order_summary"
  post '/users/:user_id/address', to: "addresses#create", as: "create_user_address"
  put '/users/:user_id/address/:id', to: "addresses#update", as: "update_user_address"
  delete '/users/:user_id/address/:id', to: "addresses#destroy", as: "delete_user_address"
  put '/products/update', to: "carts#update_cart_item", as: "update_cart_item"
  delete '/products/:product_id', to: "carts#delete_cart_item", as: "delete_cart_item"
  post '/products/:product_id/reviews/new', to: "reviews#create", as: "create_product_review"
  put '/products/:product_id/reviews/:id', to: "reviews#update", as: "update_product_review"
  delete '/products/:product_id/reviews/:id', to: "reviews#destroy", as: "destroy_product_review"
  get '/wishlist', to: "wishlists#my_wishlist", as: "my_wishlist"
  get '/cart', to: "carts#my_cart", as: "my_cart"
  post '/products/add', to: "carts#add_product_to_cart", as: "add_product_to_cart"
  post '/products/wishlist', to: "wishlists#add_product_to_wishlist", as: "add_product_to_wishlist"
  get '/products/category/:category_id', to: "home_pages#products_by_category", as: "products_by_category"
  get '/products/:id', to: "products#show", as: "product_show"
  delete '/products/:id/image/:image_id', to: "products#remove_product_image", as: "remove_product_image"
  post '/sellers/:seller_id/products/new', to: "products#create"
  delete '/sellers/:seller_id/products/:id', to: "products#destroy", as: "delete_seller_product"
  put '/sellers/:seller_id/products/:id', to: "products#update", as: "update_seller_product"

  resources :sellers do
    resources :products
  end
  resources :products do
    resources :reviews
  end
  root to: "home_pages#index"
  get 'home_pages/index'
  devise_for :users, controllers: {sessions: 'users/sessions', :registrations => "users/registrations",
  }
  resources :users do
    resources :addresses
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  before_action :set_product


  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = @product.reviews.all
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @review = @product.reviews.new
    @review.user_id = current_user.id
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = @product.reviews.new(review_params)
    @review.user_id = current_user.id

    respond_to do |format|
      if @review.save
        format.html { redirect_to product_show_path(@product.id), notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to product_show_path(@product.id), notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to product_show_path(@product.id), notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def set_product
    @product = Product.find(params[:product_id])
  end
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      set_product
      @review = @product.reviews.where(id: params[:id], user_id: current_user.id).first
    end

    # Only allow a list of trusted parameters through.
    def review_params
      params.require(:review).permit([:ratings, :description, :title])
    end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.haml
%h2
  Reviewing for
%h5=@product.name
%h5=@product.title
- if @review.errors.any?
  #error_explanation
    %h2= "#{pluralize(@review.errors.count, "error")} prohibited this review from being saved:"
    %ul
      - @review.errors.full_messages.each do |message|
        %li= message
.field
  = f.label :ratings
  = f.number_field :ratings, min: 0
.field
  = f.label :title
  = f.text_field :title
.field
= f.label :description
= f.text_field :description
.actions
  = f.submit 'Save'

app/views/reviews/_review.html.haml
- if !@reviews.nil? && @reviews.length > 0
  -@reviews.each do |review|
    %h3= review.title
    %h5= review.ratings
    %p=review.description
-else
  No Reviews Posted Yet

app/views/reviews/edit.html.haml
%h1 Editing review
= form_for @review, url: update_product_review_path(@product.id, @review.id), html: {method: :put} do |f|
  = render 'form', f: f
= link_to 'Back', product_show_path(@product.id)

app/views/reviews/index.html.haml
%h1 Listing reviews

%table
  %thead
    %tr
      %th
      %th
      %th

  %tbody
    - @reviews.each do |review|
      %tr
        %td= link_to 'Show', review
        %td= link_to 'Edit', edit_review_path(review)
        %td= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Review', new_review_path

app/views/reviews/new.html.haml
-#%h1 New review
.container.mt-5.mt-6
= form_for @review, url: create_product_review_path(@product.id), html: {method: :post} do |f|
  = render 'form', f: f

= link_to 'Back', product_show_path(@product.id)

app/views/reviews/show.html.haml
-#%p#notice= notice


-# = link_to 'Edit', edit_product_review_path(@review.id)
-#\|
-# = link_to 'Back', reviews_path